@startuml 14-day-challenge

title 14 Day Fukumi Challenge

actor "Admin" as admin
participant "Mobichat" as mc
participant "WhatsApp" as wa
actor "Customer" as customer
participant "N8N" as n8n
participant "MySQL" as db
participant "Fukumi App" as app

group Admin Perspective [Initiate Program]
    admin -> mc: << Send Broadcast Program >>
    mc -> wa: << Send Broadcast Program >>
    note right
        hanya orang yang ke tag `pejuang_fukumi_*` -> * nomer yang bakal di broadcast
        kata kunci - 14-day training challenge FUKUMI
    end note
end

||20||

group Customer Perspective [Receive Program]
    wa -> customer: << Broadcast Program Received >>
    customer -> wa: << Response Program >>
    wa -> n8n ++: << Process Program Response >>

    alt Program Rejected
        n8n -> n8n: << Generate Response >>
        n8n -> wa: << Send Response >>
        wa -[#Red]> customer: << Send Response >>
    else Program Accepted
        n8n -> app: << Generate Transaction Data >>
        app --> db: << Insert Transaction Data >>
        n8n -> n8n: << Transaction Pending for Sending Package >>
        n8n -> wa --: << Send Response >>
        wa -[#Green]> customer: << Send Response >>
    end
end

||20||

admin -->?: << Send Package >>
admin -> app: << Update Transaction Status to `Package Sent` >>

||20||

group Customer Perspective [Receive Package]
    ?-[#Green]>customer: << Package Received >>
    customer -> wa: << Scan QR Code & wa.me >>
    wa -> n8n: << User receive the package >>
    n8n -> app: << Update Transactions >>
    app -> db: << Update Transactions >>
    app -> app: << Activate Challenge Tracking >>
    app -> n8n: << Challenge Tracking Activated >>
end

||20||

loop 14 days [Daily Notifications]
    n8n -> app: << Check Challenge Tracking >>
    app -> db: << Pull Ongoing Challenge Tracking >>
    db --> app: << Challenge >>
    app -> n8n: << Challenge >>
    alt Challenge Tracking is Active
        group Daily Notifications [Daily Notifications]
            n8n -> mc: << Generate Mobiflow Form >>
            mc -> n8n: << Form >>
            n8n -> db: << Insert Today Transaction Form >>
            n8n -> wa: << Send Form to User >>
            wa -> customer: << Form >>
        end

        group User Perspective [User Filling Form]
            customer -> mc: << Filling Form >>
            mc -> n8n: << Webhook Call >>
            n8n --> app: << Call API Update Transactions >>
            n8n -> wa: << Send Response >>
            wa -[#Green]> customer: << Send Response >>
        end

        group Checking Transaction [Finish Challenge]
            n8n -> n8n: << Check Challenge Finished >>
            n8n -> app: << Check Challenge Finished >>
            app -> db: << Pull Finished Challenge Tracking >>
            db --> app: << Finished Challenge Tracking >>
            app -> n8n: << Finished Challenge Tracking >>
            n8n -> mc: << Replied Thankyou >>
            mc -> wa: << Send Thankyou Message >>
        end
    else Challenge Tracking is not Active
        n8n -> n8n: << Bypass Process >>
    end
end

||20||

@enduml